# -*- coding: utf-8 -*-
"""day11_part 2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DvFmi0dRM_1r3vwxOIlfo-o5-PzU3hT9

**TASK 2**
"""

pip install pandas

import pandas as pd

"""**TASK 3**"""

import numpy as np

np.random.randint(low =1, high=100)

"""**TASK 4**"""

import sys

sys.path

"""**TASK 5**"""

pip install Django

pip uninstall Djnago